name: taler
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_fonts: any
  intl: any
  font_awesome_flutter: any
  url_launcher: any
  iconly: any
  cupertino_icons: any
  flutter_screenutil: any
  loading_animation_widget: any
  flutter_animate: any
  http: any
  loading_animations: any
  cached_network_image: any
  badges: any
  toastification: any
  animated_custom_dropdown: any


  firedart: ^0.9.0
  google_sign_in: any
  firebase_core: any
  firebase_auth: any
  connectivity_plus: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assests/