name: taler
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  fluttertoast: any
  google_fonts: any
  intl: any
  sqflite: any
  path: any
  shared_preferences: any
  font_awesome_flutter: any
  flutter_slidable: any
  google_nav_bar: any
  avatar_glow: any
  progress_indicators: any
  url_launcher: any
  iconly: any
  cupertino_icons: any
  flutter_screenutil: any
  flutter_svg: any
  loading_animation_widget: any
  flutter_animate: any
  provider: any
  auto_size_text: any
  http: any
  loading_animations: any
  cached_network_image: any

  firebase_core: any
  firebase_auth: any
  firedart: any
  google_sign_in: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700